### PR TITLE
chore: bump azure cli 2.10.1 and Terraform 0.13.0

### PR DESCRIPTION
**Pull request by ericis**
Adds a `2.10.1` version of the Azure CLI

### CODE REVIEW

**Comment by ericis** [comment]
Hey @bgauduch, here is the latest Azure CLI. Let me know if you'd like me to make any other changes.

**Comment by ericis** [comment]
Thanks @bgauduch . Suggestions implemented.

**Comment by ericis** [comment]
... assuming you know I don't have merge permissions and will perform the merge when you have time 😃

**Comment by bgauduch** [comment]
@ericis Absolutely, i'm not in front of a computer right now and will merte asap (I prefere to keep an eye on github actions especially when releasing) 😉

**Comment by bgauduch** [comment]
@ericis merge & release done: https://github.com/Zenika/terraform-azure-cli/releases/tag/4.6

**Pull request merged**
